[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true
  headers = { "Content-Type" = "application/json" }
